name: Staic Analysis

on:
  pull_request:
      branches: [ "develop", "master", "uhm0311/analysis" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup
      uses: ./.github/actions/setup
    - name: Run Cppcheck
      run: cppcheck --enable=warning --suppress=normalCheckLevelMaxBranches --std=c99 --output-file=./report.txt --inconclusive --library=posix --force ./
    - name: Comment Report To PR
      uses: ./.github/actions/comment
  clang-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Clang Analyzer
        run: scan-build make 2>./report.txt
      - name: Comment Report To PR
        uses: ./.github/actions/comment
